env:
  browser: true
  webextensions: true
  es5: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 5
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
